#!/bin/sh
# Получаем имя текущей ветки
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Добавляем [BRANCH_NAME] в начало сообщения коммита
# Параметр $1 – путь к файлу с сообщением коммита
sed -i.bak -e "1s|^|[$BRANCH_NAME] |" "$1"
